// Generated by scripts/build-landmarks.ts — do not edit by hand.
//
// Source: Wikidata (https://query.wikidata.org/sparql), CC0. Places within 14km of a destination
// whose class is one a traveller navigates by, ranked by sitelink count and
// capped at 2 per city. Reviewed by eye before shipping.
//
// A curated entry in EXTRA_PLACES wins over anything here. Arabic falls back to
// the English name where Wikidata has no Arabic label; an untranslated proper
// noun is honest, an invented one is not.

export interface GeneratedLandmark {
  id: string;
  destinationId: string;
  name: { en: string; ar: string };
  coordinates: { lat: number; lng: number };
}

export const GENERATED_LANDMARKS: GeneratedLandmark[] = [
  { id: "lm-sheikh-zayed-mosque", destinationId: "dest-abu-dhabi", name: { en: "Sheikh Zayed Mosque", ar: "جامع الشيخ زايد" }, coordinates: { lat: 24.412, lng: 54.474 } },
  { id: "lm-louvre-abu-dhabi", destinationId: "dest-abu-dhabi", name: { en: "Louvre Abu Dhabi", ar: "اللوفر أبو ظبي" }, coordinates: { lat: 24.533, lng: 54.40001 } },
  { id: "lm-goreme-national-park", destinationId: "dest-cappadocia", name: { en: "Göreme National Park", ar: "منتزه جوريم الوطني" }, coordinates: { lat: 38.652777777, lng: 34.863055555 } },
  { id: "lm-great-pyramid-of-giza", destinationId: "dest-cairo", name: { en: "Great Pyramid of Giza", ar: "الهرم الأكبر" }, coordinates: { lat: 29.97915, lng: 31.13422 } },
  { id: "lm-giza-pyramid-complex", destinationId: "dest-cairo", name: { en: "Giza pyramid complex", ar: "مجمع أهرامات الجيزة" }, coordinates: { lat: 29.976111, lng: 31.132778 } },
  { id: "lm-koutoubia-mosque", destinationId: "dest-marrakech", name: { en: "Koutoubia Mosque", ar: "جامع الكتبية" }, coordinates: { lat: 31.624124, lng: -7.993541 } },
  { id: "lm-castle-of-good-hope", destinationId: "dest-cape-town", name: { en: "Castle of Good Hope", ar: "قلعة الرجاء الصالح" }, coordinates: { lat: -33.925908, lng: 18.427725 } },
  { id: "lm-table-mountain-national-park", destinationId: "dest-cape-town", name: { en: "Table Mountain National Park", ar: "Table Mountain National Park" }, coordinates: { lat: -33.9667, lng: 18.425 } },
  { id: "lm-museo-del-prado", destinationId: "dest-madrid", name: { en: "Museo del Prado", ar: "متحف ديل برادو" }, coordinates: { lat: 40.413888888, lng: -3.692222222 } },
  { id: "lm-museo-nacional-centro-de-arte-reina-sofi", destinationId: "dest-madrid", name: { en: "Museo Nacional Centro de Arte Reina Sofía", ar: "متحف الملكة صوفيا المركزي الوطني للفنون" }, coordinates: { lat: 40.40857143, lng: -3.6939961 } },
  { id: "lm-belem-tower", destinationId: "dest-lisbon", name: { en: "Belém Tower", ar: "برج بيليم" }, coordinates: { lat: 38.691388888, lng: -9.215833333 } },
  { id: "lm-lisbon-cathedral", destinationId: "dest-lisbon", name: { en: "Lisbon Cathedral", ar: "كاتدرائية لشبونة" }, coordinates: { lat: 38.70985, lng: -9.132983333 } },
  { id: "lm-milan-cathedral", destinationId: "dest-milan", name: { en: "Milan Cathedral", ar: "كاتدرائية ميلانو" }, coordinates: { lat: 45.463968, lng: 9.190578 } },
  { id: "lm-santa-maria-delle-grazie", destinationId: "dest-milan", name: { en: "Santa Maria delle Grazie", ar: "كنيسة سانتا ماريا ديلي غراسي" }, coordinates: { lat: 45.465833333, lng: 9.171111111 } },
  { id: "lm-st-mark-s-basilica", destinationId: "dest-venice", name: { en: "St Mark's Basilica", ar: "كنيسة القديس مرقس" }, coordinates: { lat: 45.434444444, lng: 12.339722222 } },
  { id: "lm-doge-s-palace", destinationId: "dest-venice", name: { en: "Doge's Palace", ar: "قصر دوجي" }, coordinates: { lat: 45.433666666, lng: 12.340416666 } },
  { id: "lm-uffizi-gallery", destinationId: "dest-florence", name: { en: "Uffizi Gallery", ar: "معرض أوفيزي" }, coordinates: { lat: 43.768333333, lng: 11.255277777 } },
  { id: "lm-florence-cathedral", destinationId: "dest-florence", name: { en: "Florence Cathedral", ar: "كاتدرائية فلورنسا" }, coordinates: { lat: 43.773055555, lng: 11.256944444 } },
  { id: "lm-berlin-wall", destinationId: "dest-berlin", name: { en: "Berlin Wall", ar: "جدار برلين" }, coordinates: { lat: 52.504444444, lng: 13.441111111 } },
  { id: "lm-brandenburg-gate", destinationId: "dest-berlin", name: { en: "Brandenburg Gate", ar: "بوابة براندنبورغ" }, coordinates: { lat: 52.516272222, lng: 13.377722222 } },
  { id: "lm-deutsches-museum", destinationId: "dest-munich", name: { en: "Deutsches Museum", ar: "المتحف الألماني" }, coordinates: { lat: 48.13, lng: 11.583333333 } },
  { id: "lm-nymphenburg-palace", destinationId: "dest-munich", name: { en: "Nymphenburg Palace", ar: "قصر نيمفينبورغ" }, coordinates: { lat: 48.158056, lng: 11.503611 } },
  { id: "lm-rijksmuseum", destinationId: "dest-amsterdam", name: { en: "Rijksmuseum", ar: "متحف ريكز" }, coordinates: { lat: 52.36, lng: 4.885277777 } },
  { id: "lm-van-gogh-museum", destinationId: "dest-amsterdam", name: { en: "Van Gogh Museum", ar: "متحف فان غوخ" }, coordinates: { lat: 52.358333333, lng: 4.881111111 } },
  { id: "lm-belvedere", destinationId: "dest-vienna", name: { en: "Belvedere", ar: "بيلفيدير" }, coordinates: { lat: 48.1934, lng: 16.380519444 } },
  { id: "lm-st-stephen-s-cathedral", destinationId: "dest-vienna", name: { en: "St. Stephen's Cathedral", ar: "كاتدرائية القديس إسطيفانوس" }, coordinates: { lat: 48.208427, lng: 16.373256 } },
  { id: "lm-parthenon", destinationId: "dest-athens", name: { en: "Parthenon", ar: "بارثينون" }, coordinates: { lat: 37.971527, lng: 23.726601 } },
  { id: "lm-acropolis-of-athens", destinationId: "dest-athens", name: { en: "Acropolis of Athens", ar: "أكروبوليس أثينا" }, coordinates: { lat: 37.971666666, lng: 23.726111111 } },
  { id: "lm-akrotiri", destinationId: "dest-santorini", name: { en: "Akrotiri", ar: "أكروتيري" }, coordinates: { lat: 36.35136, lng: 25.40356 } },
  { id: "lm-prague-castle", destinationId: "dest-prague", name: { en: "Prague Castle", ar: "قلعة براغ" }, coordinates: { lat: 50.09, lng: 14.4 } },
  { id: "lm-st-vitus-cathedral", destinationId: "dest-prague", name: { en: "St. Vitus Cathedral", ar: "كاتدرائية القديس فيتوس" }, coordinates: { lat: 50.090833333, lng: 14.400555555 } },
  { id: "lm-buda-castle", destinationId: "dest-budapest", name: { en: "Buda Castle", ar: "قلعة بودا" }, coordinates: { lat: 47.496111111, lng: 19.039722222 } },
  { id: "lm-aquincum", destinationId: "dest-budapest", name: { en: "Aquincum", ar: "Aquincum" }, coordinates: { lat: 47.564139, lng: 19.049472 } },
  { id: "lm-hollywood-walk-of-fame", destinationId: "dest-los-angeles", name: { en: "Hollywood Walk of Fame", ar: "ممر الشهرة في هوليوود" }, coordinates: { lat: 34.1014, lng: -118.344966666 } },
  { id: "lm-hollywood-sign", destinationId: "dest-los-angeles", name: { en: "Hollywood Sign", ar: "لافتة هوليوود" }, coordinates: { lat: 34.134102777, lng: -118.321694444 } },
  { id: "lm-golden-gate-park", destinationId: "dest-san-francisco", name: { en: "Golden Gate Park", ar: "حديقة غولدن غيت" }, coordinates: { lat: 37.769722222, lng: -122.476944444 } },
  { id: "lm-san-francisco-museum-of-modern-art", destinationId: "dest-san-francisco", name: { en: "San Francisco Museum of Modern Art", ar: "متحف سان فرانسيسكو للفن الحديث" }, coordinates: { lat: 37.785718, lng: -122.401051 } },
  { id: "lm-cn-tower", destinationId: "dest-toronto", name: { en: "CN Tower", ar: "برج سي إن" }, coordinates: { lat: 43.642752777, lng: -79.387147222 } },
  { id: "lm-royal-ontario-museum", destinationId: "dest-toronto", name: { en: "Royal Ontario Museum", ar: "متحف أونتاريو الملكي" }, coordinates: { lat: 43.66757222, lng: -79.39468333 } },
  { id: "lm-mexico-city-metropolitan-cathedral", destinationId: "dest-mexico-city", name: { en: "Mexico City Metropolitan Cathedral", ar: "كاتدرائية مكسيكو سيتي" }, coordinates: { lat: 19.4343942, lng: -99.1330824 } },
  { id: "lm-national-museum-of-anthropology", destinationId: "dest-mexico-city", name: { en: "National Museum of Anthropology", ar: "المتحف الوطني للأنثروبولوجيا" }, coordinates: { lat: 19.426111111, lng: -99.186111111 } },
  { id: "lm-christ-the-redeemer", destinationId: "dest-rio-de-janeiro", name: { en: "Christ the Redeemer", ar: "تمثال المسيح الفادي" }, coordinates: { lat: -22.951915648, lng: -43.210464122 } },
  { id: "lm-museu-nacional", destinationId: "dest-rio-de-janeiro", name: { en: "Museu Nacional", ar: "متحف البرازيل الوطني" }, coordinates: { lat: -22.905833333, lng: -43.226111111 } },
  { id: "lm-obelisco-de-buenos-aires", destinationId: "dest-buenos-aires", name: { en: "Obelisco de Buenos Aires", ar: "مسلة بوينس آيرس" }, coordinates: { lat: -34.60376, lng: -58.38162 } },
  { id: "lm-buenos-aires-cathedral", destinationId: "dest-buenos-aires", name: { en: "Buenos Aires Cathedral", ar: "Buenos Aires Cathedral" }, coordinates: { lat: -34.607408333, lng: -58.373277777 } },
  { id: "lm-osaka-castle", destinationId: "dest-osaka", name: { en: "Osaka Castle", ar: "قلعة أوساكا" }, coordinates: { lat: 34.687222222, lng: 135.525833333 } },
  { id: "lm-universal-studios-japan", destinationId: "dest-osaka", name: { en: "Universal Studios Japan", ar: "يونيفرسل ستوديوز اليابان" }, coordinates: { lat: 34.6647, lng: 135.433 } },
  { id: "lm-kyoto-imperial-palace", destinationId: "dest-kyoto", name: { en: "Kyoto Imperial Palace", ar: "القصر الإمبراطوري في كيوتو" }, coordinates: { lat: 35.025278, lng: 135.762222 } },
  { id: "lm-nijo-castle", destinationId: "dest-kyoto", name: { en: "Nijō Castle", ar: "Nijō Castle" }, coordinates: { lat: 35.014166666, lng: 135.7475 } },
  { id: "lm-changdeokgung", destinationId: "dest-seoul", name: { en: "Changdeokgung", ar: "قصر تشانغدوك" }, coordinates: { lat: 37.579444444, lng: 126.991666666 } },
  { id: "lm-gyeongbokgung", destinationId: "dest-seoul", name: { en: "Gyeongbokgung", ar: "قصر غيونغبوك" }, coordinates: { lat: 37.5798841, lng: 126.9767996 } },
  { id: "lm-forbidden-city", destinationId: "dest-beijing", name: { en: "Forbidden City", ar: "المدينة المحرمة" }, coordinates: { lat: 39.915833333, lng: 116.390833333 } },
  { id: "lm-temple-of-heaven", destinationId: "dest-beijing", name: { en: "Temple of Heaven", ar: "معبد السماء" }, coordinates: { lat: 39.8822, lng: 116.4066 } },
  { id: "lm-oriental-pearl-tower", destinationId: "dest-shanghai", name: { en: "Oriental Pearl Tower", ar: "برج لؤلؤة الشرق" }, coordinates: { lat: 31.241669444, lng: 121.494716666 } },
  { id: "lm-shanghai-museum", destinationId: "dest-shanghai", name: { en: "Shanghai Museum", ar: "متحف شانغهاي" }, coordinates: { lat: 31.230278, lng: 121.470556 } },
  { id: "lm-hong-kong-disneyland", destinationId: "dest-hong-kong", name: { en: "Hong Kong Disneyland", ar: "ديزني لاند هونغ كونغ" }, coordinates: { lat: 22.313333333, lng: 114.043333333 } },
  { id: "lm-hong-kong-museum-of-art", destinationId: "dest-hong-kong", name: { en: "Hong Kong Museum of Art", ar: "متحف هونغ كونغ للفن" }, coordinates: { lat: 22.293547222, lng: 114.172025 } },
  { id: "lm-batu-caves", destinationId: "dest-kuala-lumpur", name: { en: "Batu Caves", ar: "كهوف باتو" }, coordinates: { lat: 3.2374, lng: 101.683905555 } },
  { id: "lm-national-mosque-of-malaysia", destinationId: "dest-kuala-lumpur", name: { en: "National Mosque of Malaysia", ar: "مسجد نغارا" }, coordinates: { lat: 3.141944444, lng: 101.691666666 } },
  { id: "lm-grand-palace", destinationId: "dest-bangkok", name: { en: "Grand Palace", ar: "القصر الكبير" }, coordinates: { lat: 13.750138888, lng: 100.492027777 } },
  { id: "lm-bangkok-national-museum", destinationId: "dest-bangkok", name: { en: "Bangkok National Museum", ar: "Bangkok National Museum" }, coordinates: { lat: 13.757826, lng: 100.492307 } },
  { id: "lm-red-fort", destinationId: "dest-new-delhi", name: { en: "Red Fort", ar: "لال قلعة" }, coordinates: { lat: 28.655833333, lng: 77.240277777 } },
  { id: "lm-humayun-s-tomb", destinationId: "dest-new-delhi", name: { en: "Humayun's Tomb", ar: "مقبرة همايون" }, coordinates: { lat: 28.593264, lng: 77.250602 } },
  { id: "lm-carlton-gardens", destinationId: "dest-melbourne", name: { en: "Carlton Gardens", ar: "Carlton Gardens" }, coordinates: { lat: -37.8061, lng: 144.97 } },
  { id: "lm-national-gallery-of-victoria", destinationId: "dest-melbourne", name: { en: "National Gallery of Victoria", ar: "معرض فكتوريا الوطني" }, coordinates: { lat: -37.8225, lng: 144.968888888 } },
];
